### ISSUE TITLE
Unhandled exception in thread started by sys.exceptionhook is missing

### ISSUE THREAD

**Issue by z16844** [Kjwon15/nagato#1]
Unhandled exception in thread started by lost sys.stderr
sys.exceptionhook is missing
lost sys.stderr
# 
# last 100 lines at log file

2014-05-17 19:29:34+0900 [-]     self.target.connect(address)
2014-05-17 19:29:34+0900 [-] GET http://webmail.nyc.rr.com/ HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 27.123.206.55:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] GET http://www.google.sk/search?hl=en&lr=lang_en&tbo=d&filter=0&nfpr=1&source=hp&num=100&btnG=Search&q=%22c%22+longchamp+sur+mesure+%22Powered+by+HDWiKi+V+4.0.5%22+ HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 167.246.44.230:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] GET http://www.google.sk/search?hl=en&lr=lang_en&tbo=d&filter=0&nfpr=1&num=100&btnG=Search&q=%22u%22+%22Powered+by+Discuz!+X1.5%22+longchamp+sur+mesure&start=100 HTTP/1.1
2014-05-17 19:29:34+0900 [-] GET http://www.google.sk/search?hl=en&lr=lang_en&tbo=d&filter=0&nfpr=1&source=hp&num=100&btnG=Search&q=%2283%22+%22Powered+by+Discuz!+7.1%22+longchamp+sur+mesure HTTP/1.1
2014-05-17 19:29:34+0900 [-] POST http://www.tainster.com/main/login_post HTTP/1.1
2014-05-17 19:29:34+0900 [-] GET http://www.google.sk/search?hl=en&lr=lang_en&tbo=d&filter=0&nfpr=1&num=100&btnG=Search&q=%2227%22+%22Powered+by+Discuz!+X1.5%22+longchamp+sur+mesure&start=100 HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 124.9.13.204:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] GET http://www.google.sk/search?hl=en&lr=lang_en&tbo=d&filter=0&nfpr=1&source=hp&num=100&btnG=Search&q=%2299%22+%22Powered+by+Discuz!+7.0%22+longchamp+sur+mesure HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.6.63:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT mx2.mail2000.com.tw:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] Unhandled exception in thread started by <class nagato.MagicProxy at 0xb700f41c>
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 25, in **init**
2014-05-17 19:29:34+0900 [-]     self.method_connect()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 47, in method_connect
2014-05-17 19:29:34+0900 [-]     'Proxy-agent: {1}\n\n'.format(HTTPVER, VERSION))
2014-05-17 19:29:34+0900 [-] socket.error: [Errno 104] Connection reset by peer
2014-05-17 19:29:34+0900 [-] CONNECT 66.196.118.240:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.66.181.202:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 173.194.64.27:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 27.123.206.55:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 27.123.206.55:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] Unhandled exception in thread started by <class nagato.MagicProxy at 0xb700f41c>
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 25, in **init**
2014-05-17 19:29:34+0900 [-]     self.method_connect()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 49, in method_connect
2014-05-17 19:29:34+0900 [-]     self._read_write()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 96, in _read_write
2014-05-17 19:29:34+0900 [-]     out.send(data)
2014-05-17 19:29:34+0900 [-] socket.error: [Errno 32] Broken pipe
2014-05-17 19:29:34+0900 [-] Unhandled exception in thread started by <class nagato.MagicProxy at 0xb700f41c>
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 25, in **init**
2014-05-17 19:29:34+0900 [-]     self.method_connect()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 49, in method_connect
2014-05-17 19:29:34+0900 [-]     self._read_write()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 96, in _read_write
2014-05-17 19:29:34+0900 [-]     out.send(data)
2014-05-17 19:29:34+0900 [-] socket.error: [Errno 32] Broken pipe
2014-05-17 19:29:34+0900 [-] CONNECT 65.55.33.135:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 124.11.26.22:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 211.20.188.150:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] Unhandled exception in thread started by <class nagato.MagicProxy at 0xb700f41c>
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 28, in **init**
2014-05-17 19:29:34+0900 [-]     self.method_others()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 64, in method_others
2014-05-17 19:29:34+0900 [-]     self._read_write()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 89, in _read_write
2014-05-17 19:29:34+0900 [-]     data = _in.recv(BUFLEN)
2014-05-17 19:29:34+0900 [-] socket.error: [Errno 104] Connection reset by peer
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.6.65:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.5.76:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] Unhandled exception in thread started by <class nagato.MagicProxy at 0xb700f41c>
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 25, in **init**
2014-05-17 19:29:34+0900 [-]     self.method_connect()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 45, in method_connect
2014-05-17 19:29:34+0900 [-]     self._connect_target(self.path)
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 76, in _connect_target
2014-05-17 19:29:34+0900 [-]     self.target.connect(address)
2014-05-17 19:29:34+0900 [-]   File "/usr/lib/python2.7/socket.py", line 224, in meth
2014-05-17 19:29:34+0900 [-]     return getattr(self._sock,name)(*args)
2014-05-17 19:29:34+0900 [-] socket.error: [Errno 110] Connection timed out
2014-05-17 19:29:34+0900 [-] CONNECT 72.167.238.201:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 27.123.206.55:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 207.46.8.199:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 125.227.0.30:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.6.56:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 66.196.118.37:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.6.54:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 66.196.118.37:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 216.82.241.100:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 27.123.206.55:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] POST http://www.tainster.com/main/login_post HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 173.194.64.26:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 74.125.25.27:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.5.59:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.5.69:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 168.95.5.28:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] GET http://webmail.nyc.rr.com/ HTTP/1.1
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.119:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] CONNECT 203.188.197.111:25 HTTP/1.0
2014-05-17 19:29:34+0900 [-] Traceback (most recent call last):
2014-05-17 19:29:34+0900 [-]   File "/usr/local/bin/nagato", line 9, in <module>
2014-05-17 19:29:34+0900 [-]     load_entry_point('nagato==0.0.0', 'console_scripts', 'nagato')()
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/__init__.py", line 123, in main
2014-05-17 19:29:34+0900 [-]     handler=MagicProxy)
2014-05-17 19:29:34+0900 [-]   File "/usr/local/lib/python2.7/dist-packages/nagato/**init**.py", line 115, in start_proxy
2014-05-17 19:29:34+0900 [-]     thread.start_new_thread(handler, conn + (timeout,))
2014-05-17 19:29:34+0900 [-] thread.error: can't start new thread

**Comment by tribela** [comment]
Thanks for notice this.
But I'll check later.

**Comment by tribela** [comment]
Too many threads. It need to join threads or take another method to handle socket.

**Comment by tribela** [comment]
I totally rebuild this project using `asyncio`
This problem is fixed.
